In [1]:
import numpy as np

def add(x, y): # add
   return x + y
def subtract(x, y): # subtract
   return x - y
def multiply(x, y): # multiply
   return x * y
def divide(x, y): # divide
   return x / y



size = int(input("Enter the no of elements in the Numpy array "))
ar1 = np.zeros(size,dtype=int)
ar2 = np.zeros(size,dtype=int)
u = len(ar1)
i=0
j=0

while i < u :
    x = int(input("Enter the element in Ist array "))
    ar1[i] = x
    i+=1

print(ar1)
i=0
j=0
while i < u :
    x2 = int(input("Enter the element in 2nd array "))
    ar2[i] = x2
    i+=1

print(ar2)


print("1. Addittion")
print("2. Subtraction")
print("3. Multiplication")
print("4. Division")
choice = input("Enter the operation (1/2/3/4)")

if choice == '1':
   print(ar1,"+",ar2,"=", add(ar1,ar2))
elif choice == '2':
   print(ar1,"-",ar2,"=", subtract(ar1,ar2))
elif choice == '3':
   print(ar1,"*",ar2,"=", multiply(ar1,ar2))
elif choice == '4':
   print(ar1,"/",ar2,"=", divide(ar1,ar2))
else:
    print("Input invalid")

Enter the no of elements in the Numpy array 3
Enter the element in Ist array 1
Enter the element in Ist array 2
Enter the element in Ist array 2
[1 2 2]
Enter the element in 2nd array 7
Enter the element in 2nd array 7
Enter the element in 2nd array 7
[7 7 7]
1. Addittion
2. Subtraction
3. Multiplication
4. Division
Enter the operation (1/2/3/4)3
[1 2 2] * [7 7 7] = [ 7 14 14]
